### ISSUE TITLE
On state change and component re-rendering animation becomes junky (renew)

### ISSUE THREAD

**Issue by usamaabutt** [nandorojo/moti#174] opened 2022-02-22 08:35 UTC
Hi @nandorojo sorry to create a new ticket here but I guess the [previous ticket](https://github.com/nandorojo/moti/issues/159) is closed that's why you are not getting notified of my messages properly over there.

Please try to get some time to assist me with this [issue](https://github.com/nandorojo/moti/issues/159) You will find all the details [here](https://github.com/nandorojo/moti/issues/159)
Thanks!

**Comment by nandorojo** [comment] 2022-02-22 11:41
it looks like it's because your keys are messed up. look at the warning.

**Comment by usamaabutt** [comment] 2022-02-25 14:24
@nandorojo I have tested the `duration` value with numbers it didn't make any difference and I didn't get about the `keys` can you please correct this [code](https://github.com/nandorojo/moti/issues/159#issuecomment-1046217744) a bit in the way that it will works according to my scenario or guide me more.
Thanks looking forward to hearing from you.

**Comment by nandorojo** [comment] 2022-02-25 20:31
Unfortunately not, I suggest trying to get a hand from someone who can suggest React Native tips. If you find an issue that is reproducibly wrong with Moti, and create an Expo Snack that shows the incorrect behavior, I'm happy to take a look. As far as I can tell, you're trying to achieve what Catalin Miron did successfully in [this video](https://www.youtube.com/watch?v=hTmkjdKO3_M&t=417s). I recommend trying to copy that and see where it's different.

**Comment by nandorojo** [comment] 2022-03-10 19:54
closing for #177

**Closed by nandorojo** 2022-03-10 19:54 UTC
