### ISSUE TITLE
 ReferenceError: Property 'Proxy' doesn't exist, js engine: hermes [Mon Feb 08 2021 19:21:54.427]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes

### ISSUE THREAD

**Issue by kaneki666** [nandorojo/moti#13] opened 2021-02-08 13:24 UTC
when i  import {View as MotiView} from 'moti';
i get this error only then.
 "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "moti": "^0.4.1",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-bootsplash": "^3.1.3",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "2.0.0-rc.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1"

**Comment by nandorojo** [comment] 2021-02-08 14:21
Please follow the installation instructions entirely.

If you have, then you must be facing an issue with Reanimated: https://github.com/software-mansion/react-native-reanimated/issues/1439

I'm closing this since it's reanimated specific and not reproducible.

**Comment by kaneki666** [comment] 2021-02-08 14:26
i followed the all instruction... i have installed reanimated 2 properly run a example and it works..can you make a example repo of moti so we can play around

**Comment by nandorojo** [comment] 2021-02-08 14:44
Please make an empty expo project to try to reproduce it. I've tested this successfully on web and native with `2.0.0-rc.0`.

There's also an examples folder on this repo.

This looks like a reanimated problem, but see if you can recreate it in an empty project.

**Comment by ghmeec** [comment] 2021-02-08 21:49
am getting the same error, the app is created with react native cli and followed all the instruction for installing react native reanimated 2, it only breaks when i import {View,...} from 'moti'

environment
"moti": "^0.4.1",
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-reanimated": "2.0.0-rc.0"

**Comment by nandorojo** [comment] 2021-02-08 21:54
What happens if you try with Expo? It works fine on Expo for me, so it seems like a Reanimated issue.

**Comment by kaneki666** [comment] 2021-02-09 06:01
it only gives me the error when I import moti components..I have run reanimated  animation it works fine!
i don't use expo

**Comment by kaneki666** [comment] 2021-02-09 06:02
> am getting the same error, the app is created with react native cli and followed all the instruction for installing react native reanimated 2, it only breaks when i import {View,...} from 'moti'
> 
> environment
> "moti": "^0.4.1",
> "react": "16.13.1",
> "react-native": "0.63.4",
> "react-native-reanimated": "2.0.0-rc.0"

same dude

**Comment by nandorojo** [comment] 2021-02-09 13:46
Without a reproducible example, I don't really know what I can do.

**Comment by nandorojo** [comment] 2021-02-09 13:53
There are 2 examples in the `/examples` folder if you want to try running them.

**Comment by kaneki666** [comment] 2021-02-09 14:09
> There are 2 examples in the `/examples` folder if you want to try running them.
> 
> https://github.com/nandorojo/moti/tree/master/examples
With expo yes its working fine. Love the library nice and simple.

if you get time can u make a example with react native cli so we can use this library in production apps.. I tried two new app same error

**Comment by nandorojo** [comment] 2021-02-09 14:10
Can you upload those examples to a reproducible GitHub repo?

**Comment by nandorojo** [comment] 2021-02-09 14:11
@cmaycumber have you used a react native CLI example in a monorepo before? I wonder if the setup would be similar to the expo one.

**Comment by kaneki666** [comment] 2021-02-09 14:17
> Can you upload those examples to a reproducible GitHub repo?

here is the repo .. i Have installed moti in the reanimated playground repo
https://github.com/kaneki666/moti_demo

**Comment by nandorojo** [comment] 2021-02-09 14:34
Is this on android?

**Comment by kaneki666** [comment] 2021-02-09 14:38
> Is this on android?

yes pixel 2!

**Comment by nandorojo** [comment] 2021-02-09 14:39
Got it, could you try running this repo's examples on android and see what happens?

**Comment by kaneki666** [comment] 2021-02-09 14:42
> Got it, could you try running this repo's examples on android and see what happens? I haven't tested on android.

Yes i have tested reanimated example they work fine!
![Screenshot (Feb 9, 2021 8_41_55 PM)](https://user-images.githubusercontent.com/41444793/107379670-5d612700-6b17-11eb-83a8-fafa0e26a477.png)

**Comment by nandorojo** [comment] 2021-02-09 14:44
Can you try moti's example?

Just clone this repo, run `yarn install`, `cd examples/with-expo`, `yarn install && yarn android`

**Comment by kaneki666** [comment] 2021-02-09 14:45
oh your expo example works fine i had cloned it and run it..it works

**Comment by cmaycumber** [comment] 2021-02-09 15:06
> @cmaycumber have you used a react native CLI example in a monorepo before? I wonder if the setup would be similar to the expo one.

Not specifically. I have set up a monorepo outside of the expo managed workflow in the past and it was more difficult to get working. Most of the issues I ran into was related to the file paths that are default for a react-native project.

**Comment by ghmeec** [comment] 2021-02-09 15:26
> What happens if you try with Expo? It works fine on Expo for me, so it seems like a Reanimated issue.

it works fine with expo

**Comment by nandorojo** [comment] 2021-02-09 15:30
> > What happens if you try with Expo? It works fine on Expo for me, so it seems like a Reanimated issue.
> 
> 
> 
> it works fine with expo

I can try to make a react native CLI project when I have time, but if someone else could try debugging by commenting out different parts of the code until it works that would be useful. I don't use react native CLI.

**Comment by kaneki666** [comment] 2021-02-09 15:46
there is no file named that..there is use-map-animate-to-style.ts

**Comment by nandorojo** [comment] 2021-02-09 15:47
Oh sorry typo, that's what I meant.

**Comment by kaneki666** [comment] 2021-02-09 15:48
ok i will try what u asked 
u meant style variable right 240 line!

**Comment by nandorojo** [comment] 2021-02-09 15:52
That's right! I would try commenting out everything inside of it (but still return an object), and putting console logs throughout, until you can find the line that breaks it.

**Comment by kaneki666** [comment] 2021-02-09 15:59
got a new kind of error..i tried to run Animated Presence error...and i have returned only obj still same error..might be some other library causing it

ReferenceError: Property 'Proxy' doesn't exist, js engine: hermes
(node:7216) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [HasteMap]. Use emitter.setMaxListeners() to increase limit
[Tue Feb 09 2021 21:57:32.479]  ERROR    Error: Requiring module "node_modules\framer-motion\dist\framer-motion.cjs.js", which threw an exception: ReferenceError: Property 'Proxy' doesn't exist, js engine: hermes

**Comment by nandorojo** [comment] 2021-02-09 16:36
This all looks like it's related to Hermès/reanimated

**Comment by kaneki666** [comment] 2021-02-11 12:44
Any update? did you try it on bare rn cli?

**Comment by nandorojo** [comment] 2021-02-11 18:44
It would appear that Framer Motion uses `Proxy`, and Moti imports `framer-motion`. Hermes doesn't support `Proxy`, so we need a way around that. 

I might have to disable `AnimatePresence` on Android if there is no polyfill for Hermes.

I wrote more here: https://github.com/software-mansion/react-native-reanimated/issues/1711

**Comment by nandorojo** [comment] 2021-02-11 18:51
I'm not using Hermes yet so I can't test this, and I don't have an Android.

Could you guys please try using this library at the root of your app before importing Moti and see if it fixes it?

https://github.com/GoogleChrome/proxy-polyfill

**Comment by kaneki666** [comment] 2021-02-11 18:53
> I'm not using Hermes yet so I can't test this, and I don't have an Android.
> 
> Could you guys please try importing this library's polyfill at the root of your app before importing Moti and see if it fixes it?
> 
> https://github.com/GoogleChrome/proxy-polyfill

Ok it's midnight here i will try it out tomorrow and let you know...just have to import this index.js right?

**Comment by nandorojo** [comment] 2021-02-11 18:55
I would think so, yes.

**Comment by redwanul10** [comment] 2021-02-13 18:43
> 
> 
> got a new kind of error..i tried to run Animated Presence error...and i have returned only obj still same error..might be some other library causing it
> 
> ReferenceError: Property 'Proxy' doesn't exist, js engine: hermes
> (node:7216) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [HasteMap]. Use emitter.setMaxListeners() to increase limit
> [Tue Feb 09 2021 21:57:32.479] ERROR Error: Requiring module "node_modules\framer-motion\dist\framer-motion.cjs.js", which threw an exception: ReferenceError: Property 'Proxy' doesn't exist, js engine: hermes

i am also facing the same error for last 2 days in react native cli!

**Comment by nandorojo** [comment] 2021-02-13 18:48
Can you try the solution I proposed then?

**Comment by nextriot** [comment] 2021-02-15 05:22
> Can you try the solution I proposed then?
> 
> [#13 (comment)](https://github.com/nandorojo/moti/issues/13#issuecomment-777711082)

I tried it. Doesn't work.

**Comment by nandorojo** [comment] 2021-02-15 05:31
Hmm okay, good to know.

I propose this:

1) do some googling to see if you can find a way to polyfill `Proxy` in a Hermès app.
2) Try using those and let me know.

If there's no luck, I'll have to disable the AnimatedPresence feature for apps using Hermès.

**Comment by nandorojo** [comment] 2021-02-15 05:34
Here is a conversation about Proxy in Hermès: https://github.com/facebook/hermes/issues/33

Please read through and see if you can try anything that might solve this. Thanks!

**Comment by nandorojo** [comment] 2021-02-15 05:38
Possible solution: upgrade to RN 64 and Hermès 0.7: https://github.com/facebook/hermes/issues/33#issuecomment-696493411

More info: https://github.com/facebook/hermes/issues/33#issuecomment-668374607

**Comment by nextriot** [comment] 2021-02-15 06:05
> Possible solution: upgrade to RN 64 and Hermès v0.7: [facebook/hermes#33 (comment)](https://github.com/facebook/hermes/issues/33#issuecomment-696493411)
> 
> More info: [facebook/hermes#33 (comment)](https://github.com/facebook/hermes/issues/33#issuecomment-668374607)
> 
> Or, try `npm install hermes-engine@v0.5.2-rc1` if you're using react native 63.x
> 
> The Hermès repo has what appears to be solutions. Unfortunately I don't have an android so I can't test this out.
> 
> I would really appreciate if everyone who has commented would help investigate and trying the solutions above so we can get to the bottom of it. Thanks!
> 
> Update, here is a relevant release for a potential fix where Hermes adds support for Proxy: https://github.com/facebook/hermes/releases/tag/v0.5.2-rc1

`install hermes-engine@v0.5.2-rc1 if you're using react native 63.x`

^^That did the trick for me. Thanks for the speedy workaround @nandorojo :)

**Comment by nandorojo** [comment] 2021-02-15 14:47
Awesome! I'll add it to the docs and then close this.

**Comment by nandorojo** [comment] 2021-02-15 19:35
Solution added to docs: https://moti-5qbvkhyh8.vercel.app/installation#hermesandroid-support

**Closed by nandorojo** 2021-02-15 19:35 UTC
