### ISSUE TITLE
[0.0.18] invalid value passed to interaction

### ISSUE THREAD

**Issue by hirbod** [nandorojo/moti#185] opened 2022-03-29 12:01 UTC
Hi @nandorojo,

tried the Canary and so far, everything was working as expected without breaking changes.
While I tried your release-note example, which was looking dope, I encountered this issue:

```tsx
<MotiPressable>
  {(interaction) => {
    return (
      <MotiView
        animate={() => {
          'worklet'

          const { pressed, hovered } = interaction.value

          return { opacity: pressed ? 0.9 : 1 }
        }}
      />
    )
  }}
</MotiPressable>
```

![IMG_8611](https://user-images.githubusercontent.com/504909/160606669-bdd00ca5-b3dc-46c7-9400-0d82a4a5c556.png)

Some informations:
- react-native-reanimated v2.5.0
- react-native-gesture-handler v2.1.1
- moti v0.18.0-alpha.10

**Comment by nandorojo** [comment] 2022-03-29 17:32
Hmm weird, thanks for sending. I haven't tried reanimated 2.5 yet, I wonder if that's related (I'm on 2.3).

**Comment by hirbod** [comment] 2022-03-29 19:15
FYI: if you're using a custom-dev-client like I do, you will need to disable expo autolinking for rea inside the package.json

```
  "expo": {
    "autolinking": {
      "exclude": [
        "react-native-reanimated"
      ]
    }
  },
```

**Comment by nandorojo** [comment] 2022-03-31 21:38
I reproduced this in my app, will investigate.

**Comment by nandorojo** [comment] 2022-03-31 21:56
Dealing with reanimated internals is tricky! Think I got it, will push shortly.

**Comment by hirbod** [comment] 2022-03-31 21:57
I am dealing with those internals since 3 days to fix an ugly bug but I am close to give up!
Thanks for investigating

**Comment by nandorojo** [comment] 2022-03-31 22:04
Hm, reanimated may not allow this specific case for some reason. Going to try to repro and send a PR. Thought I had it working, might have been mistaken.

**Comment by nandorojo** [comment] 2022-03-31 22:06
It will work for the `animate` prop, but the child as a function may not work out of the box yet.

**Comment by nandorojo** [comment] 2022-03-31 22:15
Here is a reproduction that shows it's not possible with Reanimated: https://snack.expo.dev/@beatgig/courageous-bubblegum

Will open an issue there.

**Comment by nandorojo** [comment] 2022-03-31 22:26
Closing for now since it's a reanimated issue. Will make a note of this on the canary release notes.

**Comment by hirbod** [comment] 2022-03-31 22:28
Closing this will most likely cause duplicate reports, or?

**Comment by nandorojo** [comment] 2022-03-31 22:32
I pushed a fix that solves the `animate` prop allowing a worklet. As for the `MotiPressable` child case, I added a note to the release notes:

<img width="905" alt="Screen Shot 2022-03-31 at 6 32 48 PM" src="https://user-images.githubusercontent.com/13172299/161160473-d83e2ef8-0ccb-47c0-b006-bcbd2ff70c66.png">

**Comment by nandorojo** [comment] 2022-04-25 18:36
closing, as we're beholden to reanimated for this to work and it's documented that it isn't ready yet.

**Closed by nandorojo** 2022-04-25 18:36 UTC
Labels: Reanimated Bug
