### ISSUE TITLE
Sequence not working since reanimated 2.3.0

### ISSUE THREAD

**Issue by msantang78** [nandorojo/moti#195] opened 2022-05-08 23:58 UTC
Since reanimated 2.3.0 I was no longer able to use Moti sequence animations

I'm getting the error:
```
Exception in HostFunction: Javascript worklet error
```
For any sequence animation
```js
  <MotiView from={{scale: 1}} animate={{scale: [1, 1.5, 1, 1.5, 1]}}>
    <Text>Test</Test>
  </MotiView>
```

I tested updating reanimated to different versions (even the last one) without luck

While creating a minimal app to reproduce the issue I found that the problem seems to be with the Hermes Engine. If Hermes is turned off the sequences seem to work properly

@nandorojo I created a repo using react-native init to reproduce the issue on iOS (adding only reanimated, moti, and enabling Hermes)

https://github.com/msantang78/MotiSequenceReproduction

I also added an animation with reanimated sequences and they seem to be working fine.

I hope it helps

For reference: 
I originally reported this on #131, there were other reports #140 #183

**Comment by nandorojo** [comment] 2022-05-08 23:59
can you reproduce on a snack with SDK 44?

**Comment by msantang78** [comment] 2022-05-09 00:11
But the problem seems to be with the Hermes engine, I'm not sure if there is a way of enabling Hermes on a snack

**Comment by jstheoriginal** [comment] 2022-05-17 21:57
Thanks for reporting this issue. I'm also seeing this when trying to upgrade.

The issue seems to happen when it tries to call this line, since `stepAnimation` is undefined.

https://github.com/nandorojo/moti/blob/881be888512d6cc6b8746a706601c74a2a55ecbf/packages/core/src/use-map-animate-to-style.ts#L425

It references this destructured `animation` outside of the `getSequenceArray` const, which does have a value when it's destructured, but is then undefined when it's used in getSequenceArray.

https://github.com/nandorojo/moti/blob/881be888512d6cc6b8746a706601c74a2a55ecbf/packages/core/src/use-map-animate-to-style.ts#L345

example of logs:

```
 LOG  === animation value right after destructured from animationConfig() {"animation": [Function hostFunction]}
 LOG  === getSequenceArray called for {"sequenceArray": [0.25, 1.25, 1.25, 1.25, 0.25, 0.25, 0.25, 1.25, 0.25, 0.25], "sequenceKey": "opacity"}
 LOG  === value of stepAnimation (animation) just before stepAnimation called {"stepAnimation": undefined}
```

**Comment by nandorojo** [comment] 2022-05-17 22:05
interesting find. can this be reproduced on snack?

**Comment by nandorojo** [comment] 2022-05-17 22:06
if the issue is hermes, then i assume it’s a reanimated issue? or is it the fact that i’m using a function with moti to build the sequence?

**Comment by jstheoriginal** [comment] 2022-05-17 22:15
If i disable hermes, it gets further (the result of the function at least finishes), but it's freezing for me still, so it might not be an hermes issue per se (it might just break in a different way). I'll see if a snack can use hermes.

```
 LOG  === animation value right after destructured from animationConfig() {"animation": [Function hostFunction]}
 LOG  === getSequenceArray called for {"sequenceArray": [1.25, 1.25, 0.25, 0.25, 0.25, 1.25, 1.25, 1.25, 1.25, 0.25], "sequenceKey": "scale"}
 LOG  === value of stepAnimation (animation) just before stepAnimation called {"stepAnimation": [Function hostFunction]}
 LOG  === result of getSequenceArray: {"sequence": [{"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 0.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 0.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 0.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 0.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 0.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 0.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 1.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 1.25, "type": "timing"}, {"callback": [Function hostFunction], "current": 0.25, "easing": [Function hostFunction], "onFrame": [Function hostFunction], "onStart": [Function hostFunction], "progress": 0, "startTime": 0, "startValue": 0, "toValue": 0.25, "type": "timing"}]}
```

**Comment by jstheoriginal** [comment] 2022-05-17 22:46
So even without hermes, the sequence with Moti doesn't work despite it working with Reanimated, so I'm thinking there's an issue with the function.

I took @msantang78's repo and set moti to 0.18.0 and reanimted to 2.3.1 (the highest expo 0.44 allows currently).

When you run it, you can see that only the Reanimated sequence works:

https://snack.expo.dev/lTiRIGySt

However, I also tried to get it to work on reanimated 2.2.0 (what expo 0.43 allows), and it doesn't work either for moti:

https://snack.expo.dev/NZSL2U0FE

So I don't think snacks work, unfortunately, due to the limitations of expo with reanimated.

**Comment by jstheoriginal** [comment] 2022-05-17 23:18
> or is it the fact that i’m using a function with moti to build the sequence?

So I just removed the function and just do what the function does inline and the issue doesn't happen anymore. 🎉  So it looks like it's because of the inline getSequenceArray const like you suspected.

**Comment by jstheoriginal** [comment] 2022-05-17 23:26
this patch-package diff resolves the issue.

```
diff --git a/node_modules/@motify/core/src/use-map-animate-to-style.ts b/node_modules/@motify/core/src/use-map-animate-to-style.ts
index dce4aa1..694559c 100644
--- a/node_modules/@motify/core/src/use-map-animate-to-style.ts
+++ b/node_modules/@motify/core/src/use-map-animate-to-style.ts
@@ -1,29 +1,26 @@
-import { PresenceContext, usePresence } from 'framer-motion'
-import { useCallback, useContext, useEffect } from 'react'
-import type { TransformsStyle } from 'react-native'
-import {
-  useAnimatedStyle,
-  useSharedValue,
-  withDecay,
-  withSpring,
-  withTiming,
-  withDelay,
-  withRepeat,
-  withSequence,
-  runOnJS,
-} from 'react-native-reanimated'
+import {PresenceContext, usePresence} from 'framer-motion'
+import {useCallback, useContext, useEffect} from 'react'
+import type {TransformsStyle} from 'react-native'
 import type {
   WithDecayConfig,
   WithSpringConfig,
-  WithTimingConfig,
+  WithTimingConfig
+} from 'react-native-reanimated'
+import {
+  runOnJS, useAnimatedStyle,
+  useSharedValue,
+  withDecay, withDelay,
+  withRepeat,
+  withSequence, withSpring,
+  withTiming
 } from 'react-native-reanimated'
-import { PackageName } from './constants/package-name'
+import {PackageName} from './constants/package-name'
 import type {
   MotiProps,
   MotiTransition,
   SequenceItem,
   Transforms,
-  TransitionConfig,
+  TransitionConfig
 } from './types'
 
 const debug = (...args: any[]) => {
@@ -220,6 +217,62 @@ function animationConfig<Animate>(
   }
 }
 
+const getSequenceArray = (
+  sequenceKey: string,
+  sequenceArray: SequenceItem<any>[],
+  delayMs: number,
+  config: {},
+  animation: (...props: any) => any,
+  callback: (completed: boolean, value?: any) => void
+) => {     
+  'worklet'
+  
+  const sequence: any[] = []
+
+  for (const step of sequenceArray) {
+    const shouldPush =
+      typeof step === 'object'
+        ? step && step?.value != null && step?.value !== false
+        : step != null && step !== false
+    if (shouldPush) {
+      let stepDelay = delayMs
+      let stepValue = step
+      let stepConfig = Object.assign({}, config)
+      let stepAnimation = animation
+
+      if (typeof step === 'object') {
+        // not allowed in Reanimated: { delay, value, ...transition } = step
+        const stepTransition = Object.assign({}, step)
+
+        delete stepTransition.delay
+        delete stepTransition.value
+
+        const { config: inlineStepConfig, animation } = animationConfig(
+          sequenceKey,
+          stepTransition
+        )
+
+        stepConfig = Object.assign({}, stepConfig, inlineStepConfig)
+        stepAnimation = animation
+
+        if (step.delay != null) {
+          stepDelay = step.delay
+        }
+        stepValue = step.value
+      }
+
+      const sequenceValue = stepAnimation(stepValue, stepConfig, callback)
+      if (stepDelay != null) {
+        sequence.push(withDelay(stepDelay, sequenceValue))
+      } else {
+        sequence.push(sequenceValue)
+      }
+    }
+  }
+
+  return sequence
+}
+
 export function useMotify<Animate>({
   animate: animateProp,
   from: fromProp = false,
@@ -385,55 +438,6 @@ export function useMotify<Animate>({
         continue
       }
 
-      const getSequenceArray = (
-        sequenceKey: string,
-        sequenceArray: SequenceItem<any>[]
-      ) => {
-        const sequence: any[] = []
-
-        for (const step of sequenceArray) {
-          const shouldPush =
-            typeof step === 'object'
-              ? step && step?.value != null && step?.value !== false
-              : step != null && step !== false
-          if (shouldPush) {
-            let stepDelay = delayMs
-            let stepValue = step
-            let stepConfig = Object.assign({}, config)
-            let stepAnimation = animation
-            if (typeof step === 'object') {
-              // not allowed in Reanimated: { delay, value, ...transition } = step
-              const stepTransition = Object.assign({}, step)
-
-              delete stepTransition.delay
-              delete stepTransition.value
-
-              const { config: inlineStepConfig, animation } = animationConfig(
-                sequenceKey,
-                stepTransition
-              )
-
-              stepConfig = Object.assign({}, stepConfig, inlineStepConfig)
-              stepAnimation = animation
-
-              if (step.delay != null) {
-                stepDelay = step.delay
-              }
-              stepValue = step.value
-            }
-
-            const sequenceValue = stepAnimation(stepValue, stepConfig, callback)
-            if (stepDelay != null) {
-              sequence.push(withDelay(stepDelay, sequenceValue))
-            } else {
-              sequence.push(sequenceValue)
-            }
-          }
-        }
-
-        return sequence
-      }
-
       if (key === 'transform') {
         if (!Array.isArray(value)) {
           console.error(
@@ -448,7 +452,7 @@ export function useMotify<Animate>({
 
             if (Array.isArray(transformValue)) {
               // we have a sequence in this transform...
-              const sequence = getSequenceArray(transformKey, transformValue)
+              const sequence = getSequenceArray(transformKey, transformValue, delayMs, config, animation, callback)
 
               if (sequence.length) {
                 let finalValue = withSequence(sequence[0], ...sequence.slice(1))
@@ -484,8 +488,7 @@ export function useMotify<Animate>({
         }
       } else if (Array.isArray(value)) {
         // we have a sequence
-
-        const sequence = getSequenceArray(key, value)
+        const sequence = getSequenceArray(key, value, delayMs, config, animation, callback)
         let finalValue = withSequence(sequence[0], ...sequence.slice(1))
         if (shouldRepeat) {
           finalValue = withRepeat(finalValue, repeatCount, repeatReverse)
```

**Comment by nandorojo** [comment] 2022-05-26 19:11
if that patch fixed it, why did you close your PR?

**Comment by jstheoriginal** [comment] 2022-05-26 19:15
> if that patch fixed it, why did you close your PR?

😐 I didn't close it...but it says I did. 😲

I'll reopen it.

**Comment by jstheoriginal** [comment] 2022-05-26 19:19
> > if that patch fixed it, why did you close your PR?
> 
> 😐 I didn't close it...but it says I did. 😲
> 
> I'll reopen it.

It looks like when i referenced the PR on our private repo and merged changes there, it closed the issue. Just reopened it! It definitely resolves the issue still. 💯

**Comment by johkade** [comment] 2022-07-21 08:34
just fyi: this is still the case with moti 0.18, also the patch above still works 👍

**Comment by nandorojo** [comment] 2022-07-21 22:54
just merged @jstheoriginal's PR, thanks for your patience here. will release it in the next version

**Closed** 2022-07-21 22:54 UTC

**Comment by nandorojo** [comment] 2022-07-26 16:37
Sequences are now fixed in `0.19.0-alpha.2`:

`yarn add moti@canary`

Please see #215 for the upgrade guide.

Thanks guys!

**Comment by rrsalian16** [comment] 2022-07-28 20:54
@nandorojo  I loved moti,

I tried 0.19.0-alpha.2  & getting this error 

error: Error: Unable to resolve module framer-motion from /node_modules/moti/src/core/index.ts: framer-motion could not be found within the project or in these directories:
  node_modules
  ../../../node_modules
  1 | export { default as motify } from './motify'
> 2 | export { AnimatePresence } from 'framer-motion'
    |                                  ^
  3 |
  4 | export * from './types'
  5 | export { default as useAnimationState } from './use-animator'


<img width="1070" alt="Screenshot 2022-07-29 at 12 46 01 AM" src="https://user-images.githubusercontent.com/40709953/181634769-1d5ca14b-1b11-4d58-951c-30c84fc92a96.png">

**Comment by jstheoriginal** [comment] 2022-07-28 20:55
> @nandorojo  I loved moti,
> 
> 
> 
> I tried 0.19.0-alpha.2  & getting this error 
> 
> 
> 
> error: Error: Unable to resolve module framer-motion from /node_modules/moti/src/core/index.ts: framer-motion could not be found within the project or in these directories:
> 
>   node_modules
> 
>   ../../../node_modules
> 
>   1 | export { default as motify } from './motify'
> 
> > 2 | export { AnimatePresence } from 'framer-motion'
> 
>     |                                  ^
> 
>   3 |
> 
>   4 | export * from './types'
> 
>   5 | export { default as useAnimationState } from './use-animator'
> 
> 
> 
> 
> 
> <img width="1070" alt="Screenshot 2022-07-29 at 12 46 01 AM" src="https://user-images.githubusercontent.com/40709953/181634769-1d5ca14b-1b11-4d58-951c-30c84fc92a96.png">
> 
> 

Import `AnimatePresence` from `moti` instead of `framer-motion`.

**Comment by rrsalian16** [comment] 2022-07-28 21:13
> > @nandorojo  I loved moti,
> > I tried 0.19.0-alpha.2  & getting this error
> > error: Error: Unable to resolve module framer-motion from /node_modules/moti/src/core/index.ts: framer-motion could not be found within the project or in these directories:
> > node_modules
> > ../../../node_modules
> > 1 | export { default as motify } from './motify'
> > > 2 | export { AnimatePresence } from 'framer-motion'
> > 
> > 
> > ```
> > |                                  ^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 3 |
> > 4 | export * from './types'
> > 5 | export { default as useAnimationState } from './use-animator'
> > <img alt="Screenshot 2022-07-29 at 12 46 01 AM" width="1070" src="https://user-images.githubusercontent.com/40709953/181634769-1d5ca14b-1b11-4d58-951c-30c84fc92a96.png">
> 
> Import `AnimatePresence` from `moti` instead of `framer-motion`.

@jstheoriginal 
<img width="1070" alt="Screenshot 2022-07-29 at 1 12 40 AM" src="https://user-images.githubusercontent.com/40709953/181638476-2ee417ff-409b-4270-9507-e1fd67b1d08b.png">

**Comment by nandorojo** [comment] 2022-07-28 21:25
no need to quote the big messages haha

could be a caching issue?

**Comment by rrsalian16** [comment] 2022-07-28 21:29
okay, thanks @nandorojo

**Comment by nandorojo** [comment] 2022-07-28 22:10
try `yarn why framer-motion`

**Comment by rrsalian16** [comment] 2022-07-29 06:15
<img width="598" alt="Screenshot 2022-07-29 at 10 14 10 AM" src="https://user-images.githubusercontent.com/40709953/181694888-64b41f29-5600-4bed-897c-78b5827bd64d.png">

**Comment by rrsalian16** [comment] 2022-07-29 06:18
<img width="598" alt="Screenshot 2022-07-29 at 10 14 10 AM" src="https://user-images.githubusercontent.com/40709953/181695367-cf30b22e-14ec-49bf-b814-6529fcaa6408.png">

**Comment by nandorojo** [comment] 2022-07-29 11:51
🧐 what about `yarn why moti`

**Comment by rrsalian16** [comment] 2022-07-29 12:17
<img width="567" alt="Screenshot 2022-07-29 at 4 16 12 PM" src="https://user-images.githubusercontent.com/40709953/181756600-46acd45d-a6c5-4472-8caf-80a0dc891eae.png">

**Comment by nandorojo** [comment] 2022-07-29 12:18
will try to fix it today, thanks!

**Comment by rrsalian16** [comment] 2022-07-29 12:19
Okay, thank you.

**Comment by nandorojo** [comment] 2022-07-29 14:38
Can you try updating again? `yarn add moti@canary`. `0.19.0-alpha.6` should work now.

**Comment by rrsalian16** [comment] 2022-07-29 18:10
Thank you @nandorojo  It is resolved. 👏👏
