### ISSUE TITLE
Bumping/unwanted animation at each render (even if `animate` does not change) 

### ISSUE THREAD

**Issue by godness84** [nandorojo/moti#40] opened 2021-03-19 11:05 UTC
Even if `animate` prop values don't change, there's a bumping animation at each render.
- `Shape` component always uses the same `animate` values.
- `App` component triggers a re-render every time you touch the screen.
- `Shape` gets animated even if there should not be any animation.

Try this code, and touch the screen:

```typescript
import * as React from "react";
import { StyleSheet, Pressable } from 'react-native'
import { View } from 'moti'

function Shape({ bg }) {
  return (
    <View
      from={{
        opacity: 0,
        scale: 0.5,
      }}
      animate={{
        opacity: 1,
        scale: 1,
      }}
      exit={{
        opacity: 0,
        scale: 0.9,
      }}
      style={[styles.shape, { backgroundColor: bg }]}
    />
  )
}

export default function App() {
  const [visible, toggle] = React.useReducer((s) => !s, true)

  return (
    <Pressable onPress={toggle} style={styles.container}>
      <Shape bg="hotpink" key="hotpink" />
    </Pressable>
  )
}

const styles = StyleSheet.create({
  shape: {
    justifyContent: 'center',
    height: 250,
    width: 250,
    borderRadius: 25,
    marginRight: 10,
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: '#9c1aff',
  },
})
```

**Comment by nandorojo** [comment] 2021-03-19 12:45
Could you try the same thing with `useAnimatedStyle` from reanimated and see what happens when you re-render?

**Comment by godness84** [comment] 2021-03-19 13:45
`useAnimatedStyle` is not affected.

Here is the code. Only the first box is bumping, the second one (driven by `useAnimatedStyle`) is fixed.

```typescript
import * as React from "react"
import { StyleSheet, Pressable, ViewStyle } from "react-native"
import { View } from "moti"
import Animated, {
  useAnimatedStyle,
  useSharedValue,
} from "react-native-reanimated"

function Shape({ bg }: { bg: ViewStyle["backgroundColor"] }) {
  return (
    <View
      from={{
        opacity: 0,
        scale: 0.5,
      }}
      animate={{
        opacity: 1,
        scale: 1,
      }}
      exit={{
        opacity: 0,
        scale: 0.9,
      }}
      style={[styles.shape, { backgroundColor: bg }]}
    />
  )
}

function Shape2({ bg }: { bg: ViewStyle["backgroundColor"] }) {
  const offset = useSharedValue(1)

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ scale: offset.value }],
    }
  })

  return (
    <Animated.View
      style={[styles.shape, { backgroundColor: bg }, animatedStyles]}
    />
  )
}

export default function App() {
  const [visible, toggle] = React.useReducer((s) => !s, true)

  return (
    <Pressable onPress={toggle} style={styles.container}>
      <Shape bg="hotpink" key="hotpink" />
      <Shape2 bg="hotpink" key="hotpink2" />
    </Pressable>
  )
}

const styles = StyleSheet.create({
  shape: {
    justifyContent: "center",
    height: 150,
    width: 150,
    borderRadius: 25,
    marginRight: 10,
    backgroundColor: "white",
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "#9c1aff",
  },
})

```

**Comment by nandorojo** [comment] 2021-03-19 14:10
What if you use state instead of a shared value?

Also, what happens with moti 0.4.x?

**Comment by nandorojo** [comment] 2021-03-19 14:42
If this doesn't happen with `0.4.1`, then I can think of a solution. However, it might be a consequence of how reanimated tracks object changes.

**Comment by godness84** [comment] 2021-03-19 15:25
@nandorojo maybe I found the problem! 
In `use-map-animate-to-style.ts` ([line 135](https://github.com/nandorojo/moti/blob/master/packages/core/src/use-map-animate-to-style.ts#L135)) there is:
```
// solve the missing velocity bug in 2.0.0-rc.0
velocity: 2,
```

I'm using version `2.0.0` of react-native-reanimated, where this fix is not necessary anymore.
Removing that line fixes the problem.

**Comment by nandorojo** [comment] 2021-03-19 18:02
Oh good find! That's interesting. If you don't remove the line, but instead pass `transition={{ velocity: 1 }}` does that solve it too? Removing that would be a breaking change for earlier versions, so it would have to be a major release. I'll likely do this once Expo supports reanimated 2 stable.

**Comment by benvp** [comment] 2021-03-19 18:03
Hey, I think I encountered the same issue. Just wanted to open up an issue but saw this here. I have set up a sample repo and a short video displaying the issue. https://github.com/benvp/moti-spring-demo

And here the video: https://www.dropbox.com/s/xg1dku4hiid3s5y/moti-issue.mov?dl=0

**Comment by benvp** [comment] 2021-03-19 18:07
Also, when setting `transition={{ velocity: 1 }}` the animation breaks. No animation happening until it's set to `2`.

**Comment by nandorojo** [comment] 2021-03-19 18:12
@benvp Thanks for the comprehensive reproduction, very useful.

In `2.0.0-rc.0`, this workaround is needed:

```tsx
// solve the missing velocity bug in 2.0.0-rc.0
velocity: 2,
```

Maybe we could have a temporary workaround for people using newer versions of reanimated. Something like:

```js
// App.js
import { enableStableV2 } from 'moti'

enableStableV2()
```

And then we'd do this

```tsx
if (!stableV2) {
  // solve the missing velocity bug in 2.0.0-rc.0
  config = {
    velocity: 2
  }
}
```

Once Expo releases SDK 41, I can release a major version upgrade with a breaking change that removes the workaround, meaning we would only support stable versions of Reanimated 2.

---

> Also, when setting `transition={{ velocity: 1 }}` the animation breaks. No animation happening until it's set to `2`.

@benvp From my understanding, this is a reanimated bug that appears to be solved in stable v2. The best solution (for now) might be to just use `React.memo()` for components wrapping your `MotiView`.

**Comment by benvp** [comment] 2021-03-19 18:25
Don't know if it's worth adding a workaround here as someone could also wrap the exported moti `View` and set the default `velocity`. This way you wouldn't need to manage this `enableStableV2()` function and remove it later on. Just tested `React.memo()`on my example but this doesn't seem to solve it.

**Comment by nandorojo** [comment] 2021-03-19 18:27
This doesn't solve it?

```tsx
const Button = React.memo(function Button({ bg, increment }) {
  return (
    <ScaleButton onPress={increment}>
      <Shape bg="hotpink" />
    </ScaleButton>
  )
})

export default function App() {
  const [counter, increment] = React.useReducer((s) => s + 1, 0)

  return (
    <View style={styles.container}>
      <Text style={styles.counter}>{counter}</Text>
      <View style={styles.buttonContainer}>
        <Button bg="hotpink" onPress={increment} />
        <Button bg="yellow" onPress={increment} />
        <Button bg="cyan" onPress={increment} />
      </View>
    </View>
  )
}
```

**Comment by benvp** [comment] 2021-03-19 18:32
Ah interesting. This works, indeed. I only tried wrapping the `ScaleButton` in `React.memo` but this somehow didn't work. Thanks for the support and this awesome library. :)

**Comment by nandorojo** [comment] 2021-03-19 18:43
Yeah, wrapping scale button alone wouldn't work, since its `children` prop still gets recreated on every render. This is probably the biggest gotcha of `React.memo` out there: children gets a new reference each time.

**Comment by godness84** [comment] 2021-03-20 21:32
@nandorojo setting `transition={{ velocity: 1 }}` seems to fix the bumping issue (in reanimated 2.0.0). However I'm afraid that this way the animation is not very natural when the target value changes before the previous animation is ended. I only say this by looking at the code of reanimated, not by visual "feeling" - because when the new animation is applied it uses the velocity of 1 per default instead of using the current velocity.

**Comment by nandorojo** [comment] 2021-03-23 01:02
Since it seems like this is due to a bug with Reanimated's old version, I'm going to close this.

Once Reanimated v2 stable is supported by Expo (upon their release of SDK 41), I'll remove the `velocity: 2` patch. In the meantime, I recommend relying on `React.memo` (or `type: 'timing'` 😢), as I mentioned above.

I appreciate you all helping get to the bottom of this!

**Comment by nandorojo** [comment] 2021-04-01 18:30
Now that SDK 41 is out, I'm going to re-open and address this, likely with a breaking change.

**Comment by nandorojo** [comment] 2021-04-01 18:43
I just published `moti@next` at `0.7.7`, which removes `velocity: 2` from springs. Could you see if this fixes the issue? I'm still facing the problem, but only with springs. I have to do some more investigating into why it's happening.

`yarn add moti@next`

**Comment by nandorojo** [comment] 2021-04-01 19:13
Looks like it's solved for me. I'll be releasing `0.8.x` with a breaking change to upgrade to v2 stable. After that, I'll close this again.

**Comment by nandorojo** [comment] 2021-04-01 23:27
`yarn add moti` solved in 0.8!

**Closed by nandorojo** 2021-04-01 23:27 UTC

**Comment by andreasbergqvist** [comment] 2021-04-16 15:23
I have what to seem to be the problem in this issue (using moti 0.8.2)

I could look more into it, but since it seems investigated here, I ask for advice.

Here is a repo that recreate the problem:
https://github.com/andreasbergqvist/react-native-moti-test

(It is not using Expo and I've testing with both reanimated 2.0.0 and 2.1.0)

If you click the header in the app, a state if updating.
The animation created with moti is "restarting" when the component is re-rendinging. But the component using reanimated useAnimatedStyle is not. If I understand it correctly, the "moti-component" should not restart and work as the reanimated one?

moti-component: https://github.com/andreasbergqvist/react-native-moti-test/blob/main/src/components/MotiView.tsx
reanimated-component: https://github.com/andreasbergqvist/react-native-moti-test/blob/main/src/components/ReanimatedView.tsx

app, that contains the compoents and that updates the state: https://github.com/andreasbergqvist/react-native-moti-test/blob/main/src/App.tsx

**Comment by nandorojo** [comment] 2021-04-16 15:28
Could you see what happens if you use a variable that changes on each render in useAnimatedStyle? You can use an empty object as long as you declare it in render code.

Our function does that by passing the animate prop, which updates every render, so I want a good comparison.

**Comment by nandorojo** [comment] 2021-04-16 15:29
Also can you share a video of what happens? This will be easier when expo snack adds reanimated 2 this week.

**Comment by andreasbergqvist** [comment] 2021-04-16 16:21
Both animations should go from opacity 0->1 in a loop (and they do if I don't click and update state).

https://user-images.githubusercontent.com/1663126/115054337-6b00a780-9ee0-11eb-948a-c63d7e11bc14.mp4

**Comment by nandorojo** [comment] 2021-04-16 16:22
The reanimated example's UAS function doesn't receive any state variables, which is why I'd like you to use the state variables in the UAS function on the reanimated example.

**Comment by andreasbergqvist** [comment] 2021-04-16 16:45
Tried my best to "break" the reanimated animation without succeeding, will get back to test more later.

**Comment by nandorojo** [comment] 2021-04-16 16:52
Sounds good. I haven't reproduced it with expo since Moti 0.8 but I'll look into it.

**Comment by nandorojo** [comment] 2021-04-24 15:13
I published `moti@canary` with added memoization for all props (except for `animate`). 

If `animate` is never changing, you can try defining it outside of render code and passing it to the component. It will be fully memoized in the future, as mentioned on my PR: https://github.com/nandorojo/moti/pull/54

However, I can't fully memoize it yet, until this Reanimated bug is solved: https://github.com/software-mansion/react-native-reanimated/issues/1964

Part of the future of `moti` is allowing an integration with Gesture Handler, which requires not stringifying the `animate` prop to memoize it, since it needs to accept a derived value. I explain a bit more on that PR.

**Comment by andreasbergqvist** [comment] 2021-04-26 05:24
I tested updated in my test-app: https://github.com/andreasbergqvist/react-native-moti-test

And if I (as you mention) move my animate-object outside of the render function it works!

Thanks for the update and interesting findings in reanimated. Hope they can look at it soon.
As you say, the usage together with gesture handler is a really cool feature.

**Comment by nandorojo** [comment] 2021-04-26 13:47
Thanks for the update. If you leave `animate` in render, does it have the same bug?

**Comment by andreasbergqvist** [comment] 2021-04-26 14:07
Yeah, same bug.

**Comment by nandorojo** [comment] 2021-04-26 14:09
Which platform?

**Comment by andreasbergqvist** [comment] 2021-04-26 14:16
Both Android emulator and iOS simulator.
I'm using latest react-native and reanimated 2.1.0.
As seen in: https://github.com/andreasbergqvist/react-native-moti-test/blob/main/package.json

I'm not using Expo.

**Comment by nandorojo** [comment] 2021-04-26 14:17
Could you verify this happens with expo too? moti + reanimated 2 is now compatible with Expo Snack.

**Comment by andreasbergqvist** [comment] 2021-04-26 15:28
Yeah verified that the same bug remains, both on iOS and Android.
I havn't used Expo for years, so not my "normal" workflow.
And wasn't able to get reanimated 2 working in a Snack (probably just me not used of the tooling).

**Comment by nandorojo** [comment] 2021-04-26 15:35
Did you add it to the package.json?

**Comment by nandorojo** [comment] 2021-04-26 15:36
Here's a starter: https://staging.snack.expo.io/@bycedrictest/moti-starter

**Comment by andreasbergqvist** [comment] 2021-04-26 15:47
Hmm, I guess I was missing the "staging" part of the URL.
Is that some kind of preview?

Got error with babel config.
If I added it, it worked for the Android/iOS preview but not web...
See: https://snack.expo.io/@andreasitiden/thankful-chip

**Comment by nandorojo** [comment] 2021-04-26 15:51
Ah I didn't even realize it was staging. An expo employee sent me that, so looks like they haven't merged it to master yet. Maybe try adding prepending staging. I'll take a look.

**Comment by nandorojo** [comment] 2021-04-26 18:14
I don't see this issue's bug reproduced on that snack btw.

**Comment by andreasbergqvist** [comment] 2021-04-26 18:34
Yeah, I did't "implement" the issue since I had issues with the snack =)

I've updated now.
If you click "Click" at the top, the counter state is updated.

The first looping pink area is created with Moti and the second is using reanimated with useAnimatedStyle.

**Comment by nandorojo** [comment] 2021-04-26 19:00
That example doesn't exactly mimic Moti's behavior in the ReanimatedComponent. I reworked it here: https://snack.expo.io/@nandorojo/thankful-chip

The Moti and Reanimated components have the same behavior, it seems. It looks like changing `useAnimatedStyle`'s scope might stop loops? This seems specific to the loop, right? The same thing happens on the Reanimated component, so it doesn't look Moti specific to me.


https://user-images.githubusercontent.com/13172299/116136325-2921ef00-a6a0-11eb-93c7-46321d1e59ad.mp4

**Comment by andreasbergqvist** [comment] 2021-04-26 19:13
I having trouble testing in Expo, getting "Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?" error.

But yeah, you're probably right. I (obviously) don't have the same knowledge of how things work with moti and reanimated.

My concern was that I was evaluating moti in a project where I would refactor "old" animation to use moti-animations (since the value of doing it, for cleaner code, is AMAZING). But I seem to have problem with animations restarting when state is updating.

While this might be an reanimated problem, it would be great if it would be possible to fix with the PR you created.

**Comment by nandorojo** [comment] 2021-04-26 19:23
No worries, to test it out you'll need to use iOS or Android on that snack.

I'll give an update here when I'm able to merge my PR. First, I'll need the Reanimated issue I opened resolved.

For now, you should be able to solve it on moti by keeping props out of render, or by memoizing the entire component in useMemo or React.memo

**Comment by nandorojo** [comment] 2021-04-26 19:24
For context, this needs to be solved first: https://github.com/software-mansion/react-native-reanimated/issues/1964

**Comment by jay-jlm** [comment] 2021-11-21 12:57
For me, the looping animation was not following the proper initialization values across re-renders.

When clicking a button that toggles a state value,  the looping  would either stop or animate a range with a smaller range of values, depending on the when you clicked.

I was only able to solve it by moving _all the configuration properties_ outside of the render context and passing them by props. Moving only the _animate_ property (or any other combination of them) did not fix it for me.

Working code:  https://pastebin.com/HGVcVPhW
