### ISSUE TITLE
Sequences not working

### ISSUE THREAD

**Issue by davidnum** [nandorojo/moti#140] opened 2021-12-20 23:36 UTC
Hello.
Simple code from examples not working:
```jsx
<MotiView
  animate={{
    scale: [0, 1.1, { value: 1, delay: 200 }],
  }}
/>
```
Raises error: 
<img src="https://user-images.githubusercontent.com/7981854/146846344-effcb8e9-edcb-4880-b853-55cce4f1d2ee.jpeg" alt="drawing" width="300"/>
____
#### Bare react-native, not Expo
```
"moti": "0.17.1",
"react-native-reanimated": "2.3.1",
```

**Comment by nandorojo** [comment] 2021-12-20 23:39
It looks like there is an issue with sequences since reanimated 2.3. I’ve heard from a few other people. I’ll try to debug this, thanks! I’m wondering if it’s related to the Babel plug-in, because I can’t repro it in the example app of the Moti repo.

**Comment by msantang78** [comment] 2021-12-21 16:07
Tested it with moti@canary but it doesn't work

**Comment by Hirbod** [comment] 2021-12-22 09:47
I can confirm this issue. And I double checked with #141 and "EXPO_USE_EXOTIC" is not the issue here

**Comment by carlos3g** [comment] 2022-01-22 21:02
Same here. Expo sdk 44

**Comment by damian-balas** [comment] 2022-02-04 20:52
Same here. 
By the way could someone explain me how to do a play/pause loop animation?

I want a button (play / pause) that will trigger a box to spin.

Thanks!

**Comment by hirbod** [comment] 2022-02-04 22:24
This issue will be fixed once this is merged:
https://github.com/software-mansion/react-native-reanimated/pull/2851

**Comment by damian-balas** [comment] 2022-02-04 22:26
> This issue will be fixed once this is merged: [software-mansion/react-native-reanimated#2851](https://github.com/software-mansion/react-native-reanimated/pull/2851)
> 
> I checked against the branch and it is working.

Great news! :) 

By the way, would you mind to have a look?
https://github.com/nandorojo/moti/discussions/165

**Closed** 2022-02-08 01:39 UTC
