### ISSUE TITLE
useDynamicAnimation initial state when screen re-mount

### ISSUE THREAD

**Issue by filippobarcellos** [nandorojo/moti#249] opened 2022-12-21 21:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

useDynamicAnimation state returns the last state when the screen re-mount. 

### Expected Behavior

I expect the useDynamicAnimation state returns the initial state instead of the last state.

### Steps To Reproduce

```
const redCirclAnimation = useDynamicAnimation(() => {
    return {
      scale: 0,
      opacity: 0,
    };
  });

  const greenCirclAnimation = useDynamicAnimation(() => {
    return {
      scale: 1,
      opacity: 1,
    };
  });

  function onAnimate() {
    redCirclAnimation.animateTo({
      scale: [1, { value: 0, delay: 2000 }],
      opacity: [1, { value: 0, delay: 2000 }],
    });

    greenCirclAnimation.animateTo({
      scale: [0, { value: 1, delay: 2000 }],
      opacity: [0, { value: 1, delay: 2000 }],
    });
  }
```

### Versions

```markdown
- Moti: 0.11.0
- Reanimated: 2.9.1
- React Native: 0.69.4
```

### Screenshots

https://user-images.githubusercontent.com/56128203/209007243-3ed0b110-d35b-43a2-b65f-0eb595831f1b.mov

### Reproduction

1 -  green circle should appear on the first render
2 - animate and show the red circle for a few seconds then show the green again
3 - screen gets refreshed for another reason
4 - red circle appears first. (clearly, the animation is running here although I don't want this to happen)
 
How do I reset the animation after is done? I feel like I'm missing something here.

Appreciate the help.

**Comment by nandorojo** [comment] 2022-12-21 21:52
Hey, I think I’m not exactly understanding what it is that you want to happen vs. what is happening. What’s the simplest reproduction? Also, does wrapping your moti view in useMemo help?

**Comment by nandorojo** [comment] 2022-12-21 21:52
Also, can you try upgrading Moti?

**Comment by filippobarcellos** [comment] 2022-12-21 22:33
Sorry. Realized I was not clear. 

My animation consists of two things:

- First: Hide the green circle
- Second: Show the red circle
- Third Hide the red circle and show the green again.

The green circle showing is the initial value but somehow after an animation occurs when I refresh the screen the same animation is happening again. (see new video)


https://user-images.githubusercontent.com/56128203/209015171-28cdafbb-5f07-4074-a042-9c7b7ea73680.mov

**Comment by nandorojo** [comment] 2022-12-21 22:37
Is this just a fast refresh issue?

**Comment by filippobarcellos** [comment] 2022-12-21 22:38
Sorry. Realized I was not clear. 

The gist here -> https://gist.github.com/filippobarcellos/9197161e865f65442614212d7de2bbff

My animation consists of two things:

- First: Hide the green circle
- Second: Show the red circle
- Third: Reset the animation by hiding the red circle and showing the green again. (done via useDynamicAnimation)

```
redCirclAnimation.animateTo({
      scale: [1, { value: 0, delay: 2000 }],
      opacity: [1, { value: 0, delay: 2000 }],
    });

    greenCirclAnimation.animateTo({
      scale: [0, { value: 1, delay: 2000 }],
      opacity: [0, { value: 1, delay: 2000 }],
    });
```

The green circle has the initial value as this:

```
const greenCirclAnimation = useDynamicAnimation(() => {
    return {
      scale: 1,
      opacity: 1,
    };
  });
```

Somehow after an animation occurs for the first time when I refresh the screen the same animation is happening again. (see new video)

https://user-images.githubusercontent.com/56128203/209016029-f794f043-a5cd-4d94-a38a-e1f30b0174d9.mov

**Comment by nandorojo** [comment] 2022-12-21 22:40
Triggering re-renders shouldn't reset the animation state. That would be a bad behavior. In place of `forceUpdate()` just set the animation state to what you want it to be.

**Comment by nandorojo** [comment] 2022-12-21 22:42
To be honest I still don't really get what you the expected vs actual behavior is.

**Comment by filippobarcellos** [comment] 2022-12-21 22:51
That's the thing. ```forceUpdate()``` has nothing to do with the animation and somehow it seems to be affecting it.

Isn't this part resetting it?

```
greenCirclAnimation.animateTo({
      scale: [0, { value: 1, delay: 2000 }],
      opacity: [0, { value: 1, delay: 2000 }],
    });
```

In the sequence, both scale and opacity get back to 1 which is the initial value. So why when re-render the red circle is automatically animating? 

Expected behavior:

https://user-images.githubusercontent.com/56128203/209017691-be97578a-436a-4a73-bf46-beef1ef9a447.mov

Actual behavior:

https://user-images.githubusercontent.com/56128203/209017764-2b53863f-c23c-4453-aac0-42b21d643ac6.mov


When I refresh the screen I don't wanna see the red circle and somehow it gets animated.

**Comment by nandorojo** [comment] 2022-12-21 22:59
Hm, well one reason is that the components themselves are fully unmounting and then remounting. So when it remounts, it does the sequence animation. One way around it might be to hoist the variable at the top level inside of useMemo.

**Comment by filippobarcellos** [comment] 2022-12-21 23:02
Could you provide a example, please?

Thanks for your help!

**Comment by nandorojo** [comment] 2022-12-21 23:13
```tsx
function App() {
  const greenCirclAnimation = useDynamicAnimation()

  const greenCircle = useMemo(() => 
     <MotiView state={greenCirclAnimation} style={styles.goal} />, 
    []
  )

  if (forceUpdate) { 
    //...
  }

  return greenCircle
}
```

**Comment by filippobarcellos** [comment] 2022-12-22 10:00
> 



> Hm, well one reason is that the components themselves are fully unmounting and then remounting. So when it remounts, it does the sequence animation. One way around it might be to hoist the circle as a variable at the top of the component inside of useMemo.

I got that but in this case why does the animation is running? The trigger is the button. Not sure if I fully understand the use of useDynamicAnimation though.

**Comment by nandorojo** [comment] 2023-01-01 21:02
It's because reanimated takes a `style` prop, and on the first render of that component, checks if the animation has run yet or not. Because it hasn't, it re-runs since you're using a sequence. If you weren't using a sequence, this wouldn't happen. I'm going to close this since I assume that my solution would address it, unless it doesn't.

**Closed** 2023-01-31 17:37 UTC
