### ISSUE TITLE
Error with sequences on reanimated 2.3.0 stable

### ISSUE THREAD

**Issue by msantang78** [nandorojo/moti#131] opened 2021-12-10 15:32 UTC
I'm getting an error `Exception in HostFunction: Javascript worklet error` when using sequences on the latest stable version of reanimated (2.3.0)

This code works perfectly on reanimated 2.2.3 but fails on 2.3.0

```tsx
<MotiView
  animate={{
    translateY: [-10, 10, 0]
  }}
/>
```

It only fails with sequences, there is no error with the following code

```tsx
<MotiView
  animate={{
    translateY: 50
  }}
/>
```

Full Error:

```
Exception in HostFunction: Javascript worklet error

Error: Javascript worklet error
at _f (native)

Error: Exception in HostFunction: Javascript worklet error

Error: Javascript worklet error
at _f (native)
at _f (native)

reanimated::REAIOSErrorHandler::raiseSpec()
REAIOSErrorHandler.mm:18
reanimated::ErrorHandler::raise()::'lambda'()::operator()()
decltype(std::__1::forwardreanimated::ErrorHandler::raise()::'lambda'()&(fp)()) std::__1::__invokereanimated::ErrorHandler::raise()::'lambda'()&(reanimated::ErrorHandler::raise()::'lambda'()&)
void std::__1::__invoke_void_return_wrapper::__callreanimated::ErrorHandler::raise()::'lambda'()&(reanimated::ErrorHandler::raise()::'lambda'()&)
std::__1::__function::__alloc_func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocatorreanimated::ErrorHandler::raise()::'lambda'(), void ()>::operator()()
std::__1::__function::__func<reanimated::ErrorHandler::raise()::'lambda'(), std::__1::allocatorreanimated::ErrorHandler::raise()::'lambda'(), void ()>::operator()()
std::__1::__function::__value_func<void ()>::operator()() const
std::__1::function<void ()>::operator()() const
reanimated::REAIOSScheduler::scheduleOnUI(std::__1::function<void ()>)
reanimated::ErrorHandler::raise()
reanimated::NativeReanimatedModule::onRender(double)
reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1::operator()(double) const
decltype(std::__1::forward<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1&>(fp)(std::__1::forward(fp0))) std::__1::__invoke<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1&, double>(reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1&, double&&)
void std::__1::__invoke_void_return_wrapper::__call<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1&, double>(reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1&, double&&)
std::__1::__function::__alloc_func<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1, std::__1::allocator<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1>, void (double)>::operator()(double&&)
std::__1::__function::__func<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1, std::__1::allocator<reanimated::NativeReanimatedModule::NativeReanimatedModule(std::__1::shared_ptrfacebook::react::CallInvoker, std::__1::shared_ptrreanimated::Scheduler, std::__1::shared_ptrfacebook::jsi::Runtime, std::__1::shared_ptrreanimated::ErrorHandler, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, int, facebook::jsi::String const&)>, std::__1::shared_ptrreanimated::LayoutAnimationsProxy, reanimated::PlatformDepMethodsHolder)::$_1>, void (double)>::operator()(double&&)
std::__1::__function::__value_func<void (double)>::operator()(double&&) const
std::__1::function<void (double)>::operator()(double) const
invocation function for block in reanimated::createReanimatedModule(RCTBridge*, std::__1::shared_ptrfacebook::react::CallInvoker)::$_2::operator()(std::__1::function<void (double)>, facebook::jsi::Runtime&) const
-[REANodesManager onAnimationFrame:]
DF59392D-5705-3A26-B6C2-32CCCEF4EF48
DF59392D-5705-3A26-B6C2-32CCCEF4EF48
A408A063-A023-3AAA-A674-0FF01607F818
A408A063-A023-3AAA-A674-0FF01607F818
A408A063-A023-3AAA-A674-0FF01607F818
A408A063-A023-3AAA-A674-0FF01607F818
CFRunLoopRunSpecific
GSEventRunModal
F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4
UIApplicationMain
main
1A4BE407-C230-309B-AEAB-8E9C62BD377A
```

**Comment by nandorojo** [comment] 2021-12-10 15:39
Looks like Reanimated 2.3.0 must have some sort of breaking change for sequences.

Also, take a look at the edits I made to your code snippets. You can add `tsx` after the back ticks to make it format. And you can use the Prettier Chrome extension to prettify the code. Makes it easier to read.

**Comment by nandorojo** [comment] 2021-12-10 15:40
Related https://github.com/software-mansion/react-native-reanimated/issues/2527

**Comment by nandorojo** [comment] 2021-12-10 15:40
In general, I'm not using 2.3.0 yet. Even the stable one isn't stable enough for me, so I won't consider Moti to officially support it until they fix some things up. But I'll notify when it does.

**Comment by msantang78** [comment] 2021-12-10 16:00
Perfect, thanks for the quick response

**Comment by nandorojo** [comment] 2021-12-10 16:14
Closing for now, will reopen if there is movement on the stability

**Comment by nandorojo** [comment] 2021-12-15 18:38
I'm upgrading to reanimated 2.3, so I'm going to be investigating this. I've had a few issues with Reanimated 2.3: `withTiming` has some odd behavior for me for `width` and `backgroundColor`. I also heard from @ intergalacticspacehighway that sequences aren't working properly with Moti. Once I merge in #136, I'll open a PR for 2.3 support on Moti.

**Comment by nandorojo** [comment] 2021-12-15 20:31
Weirdly I haven't been able to reproduce this. Works fine for me in the example app. I'll try in my real app.

**Comment by nandorojo** [comment] 2021-12-15 21:22
Can you try on canary? It's working for me, so I'm closing unless you can reproduce it/say it still doesn't work for you.

```sh
yarn add moti@canary
```

**Closed by nandorojo** 2021-12-15 21:23 UTC
Labels: reanimated 2.3

**Comment by msantang78** [comment] 2021-12-21 15:51
Thanks for your feedback, I will test. Sorry for the delayed response

**Comment by nandorojo** [comment] 2021-12-21 15:52
Will follow up at #140
