### ISSUE TITLE
Animation issue on Android

### ISSUE THREAD

**Issue by b0n1q** [nandorojo/moti#166] opened 2022-02-07 13:56 UTC
Hey all
I'm using the latest version of the moti lab and face issues on the android device

Here is my code 
```
import { View as AnimationView } from 'moti'

<AnimationView
                    from={{
                        flex: 0,
                        backgroundColor: '#FF621F',
                        height: 10,
                    }}
                    animate={{
                        flex: 0.6,
                        backgroundColor: '#FF621F',
                        height: 10,
                    }}
                    transition={{ type: 'timing', duration: 800 }}
 />
```

on iOS everything works fine, but android shows nothing

what goes wrong?

**Comment by b0n1q** [comment] 2022-02-07 14:53
with `width` the same actually

**Comment by nandorojo** [comment] 2022-02-07 14:55
percentage needs to be a string for width

**Comment by b0n1q** [comment] 2022-02-07 15:01
I understand, but still doesn't work
on ios everything is correct

**Comment by b0n1q** [comment] 2022-02-07 15:15
> I’m not totally sure what you mean. Can you reproduce on Expo Snack?

i have updated code above, check please

**Comment by nandorojo** [comment] 2022-02-07 15:18
can you reproduce on expo snack

**Comment by b0n1q** [comment] 2022-02-07 15:21
hm, interesting, but in expo snack it works with the same code

**Comment by nandorojo** [comment] 2022-02-08 01:35
that means the issue is either something in your code or reanimated 2.3. but in either case, it seems like it's not moti, so i'm going to close this unless you can reproduce it in a snack for me to help

**Closed** 2022-02-08 01:35 UTC
