### ISSUE TITLE
MotiView mount animation is not fired in some circunstances

### ISSUE THREAD

**Issue by hlarrainq** [nandorojo/moti#332] opened 2024-01-05 01:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

MotiView mount animation is not fired in some circunstances (Android Emulator, iOS playing pip videos, and another random moments on both platforms). I have the suspect that is caused by a incompatibility from NativeBaseProvider.

### Expected Behavior

MotiView mount animation should start at any circunstance.

### Steps To Reproduce

1. Create a Expo + RN project.
2. Create a MotiView with a mount animation using from and animate props.
3. Use NativeBase and wrap the view with NativeBaseProvider
4. Open Expo Go on Android Emulator and start to use the app
5. Eventually, all animations will stop the mount transitions. (This is not fully reproducible, because sometimes works and sometime fails, i can't find the bug)

### Versions

```markdown
- Moti: 0.25.4
- Reanimated: ~3.3.0
- React Native: 0.72.4
```

### Reproduction

https://github.com/hlarrainq/moti-bug-on-mount.git

**Comment by hlarrainq** [comment] 2024-01-05 05:52
I removed NativeBaseProvider wrapper from my app, but i still get the random stuck mount animation on Android :(
Don't know how to reproduce this well, but it is affecting my users. Any help is helpful!

**Comment by nandorojo** [comment] 2024-01-07 04:31
Is your code sample reproducing it?

**Comment by hlarrainq** [comment] 2024-01-08 17:07
Hey Fernando,

I encountered the issue. The problem is related to reanimated 3.3.0

https://github.com/software-mansion/react-native-reanimated/issues/4434

I was using Expo Go with the latest version of reanimated for it, but i was able to fix it updating and creating a development build.

Thanks for your library!

**Comment by fuelkoy** [comment] 2024-01-18 06:31
@hlarrainq Thank you for the information. You pointed me to the right solution also. ❤️ 

(Btw you could probably close this issue as it is not caused by Moti 😊)

**Closed** 2024-01-18 11:36 UTC
