### ISSUE TITLE
Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by Aarchi-Ayoub** [nandorojo/moti#240] opened 2022-11-14 11:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1440" alt="Screen Shot 2022-11-14 at 12 52 12" src="https://user-images.githubusercontent.com/61331286/201653399-64bddc0e-b2ed-427e-aa03-72d94a784e7c.png">

### Expected Behavior

Cannot read properties of null (reading 'useContext')

### Versions

```markdown
"moti": "^0.20.0",
"react": "17.0.2",
"react-native": "0.68.2",
"react-native-reanimated": "^2.12.0",
```

### Screenshots

<img width="1436" alt="Screen Shot 2022-11-14 at 12 50 52" src="https://user-images.githubusercontent.com/61331286/201653137-4fe1b169-d7ef-4e08-ab2f-2574e7ac1417.png">

### Reproduction

even with docs example i fail to run it

**Comment by nandorojo** [comment] 2022-11-19 23:28
Duplicate of #201 #189 #197

Please use `npm i --legacy-peer-deps`

**Closed** 2022-11-19 23:29 UTC

**Comment by nandorojo** [comment] 2022-11-21 15:00
hmm. can you try a fresh expo app and install moti with yarn? it should work…

**Comment by alexkey89** [comment] 2022-12-29 23:18
I had the same exact issue with react-native 0.70.6. npm i moti --legacy-peer-deps did the trick.

**Comment by dumitru-buda** [comment] 2023-03-16 12:05
@alexkey89 I tried this also but after doing an `npm install` i get the same issue

**Comment by Lonka-Pardhu** [comment] 2024-11-15 11:54
this worked for me too 

`npm i moti --legacy-peer-deps`

**Comment by restoker** [comment] 2025-07-03 15:54
`npm uninstall moti`

`npm install react-native-svg`

`npm i moti --legacy-peer-deps`

this work for my
